### PR TITLE
Add auto_merge option for GitHub create a deployment API

### PR DESCRIPTION
**Pull request by kyo-nanba**
Thanks for the helpful action!

I added the "auto_merge" option.

This is a value that is passed directly to the parameter that exists in GitHub's createDeployment API. I don't think it's strange to add a value that can be set in the createDeployment API to the branch-deploy action.

I have a use case where I want to deploy a branch to a development environment without changing its current state.

### CODE REVIEW

**Comment by mungojam** [comment]
I don't think `auto_merge` is a good name for this. I had assumed it related to auto-merging of PRs which is a different thing. Perhaps `merge_from_base_branch` or something is better.

**Comment by GrantBirki** [comment]
@kyo-nanba Something that will be very important here and we should document with this feature is involving the `update_branch` parameter as seen here: https://github.com/github/branch-deploy/blob/244e514a60570e8dffcb8d4454dea0c6f4c282f9/action.yml#L64-L67

The `update_branch` parameter will always need to be set to `disabled` otherwise, the Action will never reach the part of our code where the `auto_merge` parameter is used. If you look here, we check in the `prechecks()` function for what the value of `update_branch` is set to [here](https://github.com/kyo-nanba/branch-deploy/blob/cdd497ac431de2ebbf46b4c0691493ac293a55f6/src/main.js#L345). If it is set to anything else other than `disabled` the Action will exit and it will never reach your new code.

**Comment by KevinMSampson** [comment]
I'm actually experiencing this myself on GHES. If I leave the update_branch to 'warn' by default, the precheck does not catch the base diff and warn before hitting the createDeployment call, causing the 'Auto-merge' check condition to run, updating the branch (not triggering any CI runs of course), and PR with a warning comment and not continuing. Same happens when I set it to 'disabled'.

I would love the disabled option to make sure the deployment call doesn't auto merge too.

**Comment by GrantBirki** [comment]
> I would love the disabled option to make sure the deployment call doesn't auto merge too.

@KevinMSampson Would you be able to provide screenshots or snippets of the logs when this is taking place? I haven't hit this condition myself and it is something we should certainly catch if it is happening. Thanks!

**Comment by KevinMSampson** [comment]
> Would you be able to provide screenshots or snippets of the logs when this is taking place?

@GrantBirki 

1. Created a new branch
2. Created a file on new branch
3. Created a PR for the new branch
4. Updated an existing file on main
5. Commented `.deploy noop` and it was successful
6. Commented `.deploy` and it hit the createDeployment step and stopped with the warning

Here are the run settings from the debug log. It’s a multi-job workflow, so I’m using `skip_completing`. There’s more but not sure if this is the right place to post it all

```
##[group]Run github/branch-deploy@v4.6.0
with:
  production_environment: prod
  environment_targets: sandbox,qa,prod
  environment: sandbox
  skip_completing: true
  github_token: ***
  status: success
  reaction: eyes
  trigger: .deploy
  noop_trigger: noop
  lock_trigger: .lock
  unlock_trigger: .unlock
  help_trigger: .help
  lock_info_alias: .wcid
  stable_branch: main
  prefix_only: true
  update_branch: warn
  required_contexts: false
  allow_forks: true
  admins: false
  admins_pat: false
  merge_deploy_mode: false
##[endgroup]
```

**Comment by GrantBirki** [comment]
@KevinMSampson I tried to replicate the issue you mentioned and I am unable to.

Here is what I did:

1. Created a workflow that closely replicates the one you listed above. It can be viewed [here](https://github.com/GrantBirki/actions-sandbox/blob/bc2db94f679d3817f2d8721bd5763f8806bfba97/.github/workflows/branch-deploy.yml#L21-L29)
2. I then commented `.deploy noop` (it did what it was supported to) and then commented `.deploy` and it exited with a [warning message here](https://github.com/GrantBirki/actions-sandbox/pull/33#issuecomment-1465297599) exactly as I would expect it to as well
3. The [logs](https://github.com/GrantBirki/actions-sandbox/actions/runs/4399399815/jobs/7703912904#step:2:31) for this run look as I would expect them to as well

**Comment by GrantBirki** [comment]
Ohhh maybe I'm starting to see clearly here! I just tried setting it to `update_branch: disabled` and it still updated the branch

image

If I'm understanding correctly, you explicitly do **not** want to do this when `update_branch` is set to `disabled`. When this setting is enabled, you never want the branch to updated under any conditions. Is that correct?

**Comment by KevinMSampson** [comment]
Definitely. I believe that's what the OP is asking for specifically. I think I just happen to be stumbling upon a bug as well that this feature might be able to help fix for our scenario at least

**Comment by GrantBirki** [comment]
This PR is going to be closed in favor of https://github.com/github/branch-deploy/pull/121. Thank you all for the feedback! I'll get this merged in shortly on the new PR. ❤️

**Comment by GrantBirki** [comment]
The latest release ([`v4.6.1`](https://github.com/github/branch-deploy/releases/tag/v4.6.1)) now contains these updates, enjoy! 🚀

**Comment by kyo-nanba** [comment]
Sorry for the late reply.

I think #121 is a better way. Thanks.

When I tested the operation for submit this Pull Request, I was able to reach the process where `auto_merge` was used even if `update_branch` was left as warn. So i added the `auto_merge` option without modifying the `update_branch`. 

I agree that the `auto_merge` name being confusing.

**Pull request closed without merging**
