### PR TITLE
Add checks mode input

### LINKED ISSUE #73: Bug: does not observe required checks
At the moment deploys are blocked on all status checks passing, even if they're not required.

This is because `statusCheckRollup.state` doesn't care about whether a check is required or not:

https://github.com/github/branch-deploy/blob/43afd75c657a06c55c953cc7af493d9cf565aa43/src/functions/prechecks.js#LL151

I don't know if there's an elegant way to check this 😢 (especially one that avoids paging through results). The best graphql I could come up with was this:

```
{
  repository(owner: "github", name: "branch-deploy") {
    pullRequest(number: 69) {
      reviewDecision
      commits(last: 1) {
        nodes {
          commit {
            checkSuites {
              totalCount
            }
            statusCheckRollup {
              state
              contexts(first: 100) {
                nodes {
                  ... on CheckRun {
                    isRequired(pullRequestNumber: 69)
                    conclusion
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by Ugzuzg**
Closes #73

Uses the approach suggested in the issue itself.

### CODE REVIEW

**Comment by GrantBirki** [comment]
@Ugzuzg Have you tested out all these changes in a project somewhere and confirmed that it is working as expected?

**Comment by GrantBirki** [comment]
@Ugzuzg I don't think this quite works. Here is how I tested for you to replicate:

1. I set[ `checks: required`](https://github.com/GrantBirki/actions-sandbox/blob/8086b13302e98290cf489a581032ab464eb91812/.github/workflows/branch-deploy.yml#L25) in my Actions config. I confirmed this setting was enabled by viewing my [Actions logs](https://github.com/GrantBirki/actions-sandbox/actions/runs/7939893229/job/21680526524#step:2:4)
2. I created a required CI check on my pull request
  
    image

3. I attempted to [deploy](https://github.com/GrantBirki/actions-sandbox/pull/96#issuecomment-1949784397) that branch
4. The deployment [failed](https://github.com/GrantBirki/actions-sandbox/pull/96#issuecomment-1949784763) even though the only failing CI check was one that was **not** required
    
    image

**Comment by Ugzuzg** [comment]
Thanks for pointing that out! Here's the working version: https://github.com/Ugzuzg/actions-sandbox/pull/2

I didn't notice that `checks` needed to be manually read and passed to the function.

**Review by GrantBirki — APPROVED** [review]

**Comment by GrantBirki** [comment]
@Ugzuzg your changes are live in the following pre-release! Go ahead and give it a try and I'll make it the latest release within the next week for the public to use 🎉 

https://github.com/github/branch-deploy/releases/tag/v9.1.0

**Pull request merged**
