### PR TITLE
Add `sha` to outputs

### PR DESCRIPTION
**Pull request by sinsoku**
When implementing a workflow to build a Docker image, it is useful to have `sha` in outputs.

```yaml
- name: branch-deploy
  id: branch-deploy
  uses: github/branch-deploy@vX.X.X

- name: Build and push
  uses: docker/build-push-action@v4
  with:
    tags: user/app:${{ steps.branch-deploy.outputs.sha }}
```

### CODE REVIEW

**Comment by GrantBirki** [comment]
@sinsoku can you also update the main readme to include this new `output`?

https://github.com/github/branch-deploy#outputs-

Thanks!

**Comment by sinsoku** [comment]
@GrantBirki 
I updated README.md and force-pushed.

**Review by GrantBirki — APPROVED** [review]

**Comment by GrantBirki** [comment]
Confirmed that it works https://github.com/GrantBirki/actions-sandbox/actions/runs/4355495773/jobs/7612191405#step:3:7

It should be noted it only exports the `sha` on deployments and not `noop` deploys. I'll update the readme with these notse

**Comment by GrantBirki** [comment]
New release published -> https://github.com/github/branch-deploy/releases/tag/v4.5.2

Thanks @sinsoku!

**Comment by GrantBirki** [comment]
I agree, I'll work on adding this globally for noop and true deploys shortly

**Comment by GrantBirki** [comment]
Working on this PR for this feature https://github.com/github/branch-deploy/pull/116

**Pull request merged**
